const applescript = require('applescript');
const ARTIST = 0;
const GENRE = 1;
const SONGX = 0;
const SONGY = 1;

const newSong = function () {
  getSongCount();
  isPlayerStoppedPaused();
  getNowPlaying('Name');
  getNowPlaying('Artist');
  getNowPlaying('Genre');
  getNextTanda();
  isInterstitial();
};

// Do all the things at once
newSong();

// Get the name, artist, genre of current song
function getNowPlaying(songAttribute) {
  let nowPlayingString = 'tell application "iTunes" to get ' + songAttribute + ' of current track';
  let nowPlayingElementId = 'nowPlaying' + songAttribute;
  applescript.execString(nowPlayingString, function(err, rtn) {
    if (err) {return}
    if (songAttribute === "Name") {
      // Write to the announcement div in case it's an announcement
      document.getElementById("announcementText").innerHTML = rtn ;

      // Look backwards through rtn and add a <br> before the final ( if there is one
      let finalOpenParenPosition = rtn.lastIndexOf('(');
      if (finalOpenParenPosition > -1) {
              let modifiedForParen = rtn.substring(0, finalOpenParenPosition) + '<br/> (' + rtn.substring(finalOpenParenPosition + 1);
              document.getElementById(nowPlayingElementId).innerHTML = modifiedForParen ;
      }
      else {
        document.getElementById(nowPlayingElementId).innerHTML = rtn ;
      }
    }
    else {
      document.getElementById(nowPlayingElementId).innerHTML = rtn ;
    }
  });
}

// External script: Get array with next-tanda artist and genre and write to both cortina and nextTanda divs
function getNextTanda() {
  applescript.execFile("applescript/getNextTanda.applescript", function(err, rtn) {
    if (err) {return}
    if (rtn) {
      // Write to the cortina div
      document.getElementById("cortinaNextTandaArtist").innerHTML = rtn[ARTIST];
      document.getElementById("cortinaNextTandaGenre").innerHTML = rtn[GENRE];

      // Write to the nextTanda div, with text appends as needed
      if (rtn[ARTIST].length >0) {
        document.getElementById("nextTandaArtist").innerHTML = ("<strong>NEXT TANDA:</strong> " + rtn[ARTIST]);
      }
      else {
        document.getElementById("nextTandaArtist").innerHTML = rtn[ARTIST];
      }
      if (rtn[GENRE].length >0 && !rtn[GENRE].match("Last Tanda") )  {
        document.getElementById("nextTandaGenre").innerHTML = ("&nbsp;&nbsp;|&nbsp;&nbsp;" + rtn[GENRE]);
      }
      else {
        document.getElementById("nextTandaGenre").innerHTML = rtn[GENRE];
      }
    }
  });
}

// External AppleScript: Get array with X of Y count of current tanda
function getSongCount() {
  applescript.execFile("applescript/getSongCount.applescript", function(err, rtn) {
    if (err) {return}
    if (rtn[SONGX] > 0 && rtn[SONGY] > 0) { // This prevents visual skip for negative numbers generated by cortinas
      document.getElementById("songX").innerHTML = rtn[SONGX];
      document.getElementById("songY").innerHTML = rtn[SONGY];
    }
  });
}

// Display image in overlay if player state is stopped or paused
function isPlayerStoppedPaused() {
  applescript.execString('tell application "iTunes" to get player state', function(err, rtn) {
    if (err) {return}
    if (rtn !== "playing")  {
      document.getElementById("playerStoppedPaused").style.display = "block";
    }
    else {
      document.getElementById("playerStoppedPaused").style.display = "none";
    }
  });
}

// External AppleScript: Detect interstitial; if so, display either next-tanda or announcement info and hide nowNext
function isInterstitial() {
  applescript.execFile("applescript/detectInterstitial.applescript", function(err, rtn) {
    if (err) {return}
    if (rtn[0].match("ortina"))  {
      document.getElementById("interstitial").style.display = "flex";
      document.getElementById("cortina").style.display = "block";
      document.getElementById("announcement").style.display = "none";
      document.getElementById("nowNext").style.display = "none";
    }
    if (rtn[1].match("nnounc"))  {
      document.getElementById("interstitial").style.display = "flex";
      document.getElementById("cortina").style.display = "none";
      document.getElementById("announcement").style.display = "block";
      document.getElementById("nowNext").style.display = "none";
    }
    if (!rtn[1].match("nnounc") && !rtn[0].match("ortina")) {
      document.getElementById("interstitial").style.display = "none";
      document.getElementById("cortina").style.display = "none";
      document.getElementById("announcement").style.display = "none";
      document.getElementById("nowNext").style.display = "block";
    }
  });

}
